### PR TITLE
Handle missing start_line

### LINKED ISSUE #1: Error - KeyError: 'start_line'
```
{'id': '00861528b77b7c756782680b416d8f5d0462281e2fe0720e16eeda3cffb5118b', 'category': 'sast', 'name': 'Found JAX-WS SOAP endpoint', 'message': 'Found JAX-WS SOAP endpoint', 'description': 'a.a.a.getListDevice(String) is a SOAP Web Service endpoint', 'cve': '22fbc491d9ea7cfcfbf7a63f589610b9:JAXWS_ENDPOINT:src/main/java/a/a/a/A.java:0', 'severity': 'Low', 'confidence': 'Low', 'scanner': {'id': 'find_sec_bugs', 'name': 'Find Security Bugs'}, 'location': {'file': 'src/main/java/a/a/a/a/a/A.java', 'class': 'a.a.a.a.a.A', 'method': 'getListDevice'}, 'identifiers': [{'type': 'find_sec_bugs_type', 'name': 'Find Security Bugs-JAXWS_ENDPOINT', 'value': 'JAXWS_ENDPOINT', 'url': 'https://find-sec-bugs.github.io/bugs.htm#JAXWS_ENDPOINT'}]}
Traceback (most recent call last):
  File "/usr/local/bin/ss2ju", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/secscanner2junit/__init__.py", line 34, in main
    testsuite = parser.parse()
  File "/usr/local/lib/python3.9/site-packages/secscanner2junit/sast.py", line 32, in parse
    testcases = [self.parse_findings(finding, timing) for finding in rel_find]
  File "/usr/local/lib/python3.9/site-packages/secscanner2junit/sast.py", line 32, in <listcomp>
    testcases = [self.parse_findings(finding, timing) for finding in rel_find]
  File "/usr/local/lib/python3.9/site-packages/secscanner2junit/sast.py", line 15, in parse_findings
    location_line = finding['location']['start_line']
KeyError: 'start_line'
```

### PR DESCRIPTION
**Pull request by marwin1991**
Closes #1

### CODE REVIEW

**Comment by angrymeir** [comment]
Hey @marwin1991 ,

thanks for your contribution! :)
I'll publish it directly afterward. 
Probably gonna rewrite the whole parsing to be a bit more error-resistant in the following weeks.

**Comment by marwin1991** [comment]
Really cool lib !!! ❤️ 
Did you considered building docker image with preinstalled lib?

Waiting to release :)

**Comment by marwin1991** [comment]
@angrymeir

**Comment by marwin1991** [comment]
@angrymeir 
after an update I've got error:

image
I have re-run but still the same (file was for sure, because it is commited to repo to tests)

I've mange to solve it with:
```
    - ss2ju sast ./gl-sast-report.json gl-sast-report.xml
```

It is only FYI maybe you will have the same problem :)

Anyway thank you so much!

**Pull request merged**
